// 服务器杂项协议

syntax = "proto3";

package proto;

import "define.proto";
import "server_only/config.server.proto";

option go_package = "./;proto";

// 进程检测到配置了停服维护信息
message StopServerConfigNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10072;
    }
}

// 连接上nodeserver后需要通知工作线程
message NodeserverConnectedAndRegisteredNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10098;
    }

    uint32 nodeserver_id = 1;
}

// 一个协议发送给多个玩家，服务器内部发送一条协议即可，在gameserver上对每个玩家发送一条
message MultiPlayerMsg {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10012;
    }

    repeated uint32 uid_list = 1; // UID列表
    bytes proto_bin = 2;          // 需要发送的协议
}

// gateserver向dispatch注册
message AddGateserverNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10035;
    }

    uint32 listen_port = 1; // 监听端口
    uint32 outer_ip = 2;    // 外网端口
    bool use_domain_name = 3;
    string domain_name = 4;
}

// 服务注册
message RegisterServiceNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10007;
    }

    repeated ServiceType service_type_list = 1; // 当前机器上运行的服务
}

// Game->Gate 玩家迁移
message PlayerTransferNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10021;
    }

    uint32 transfer_uid = 1; // 迁移玩家
    uint32 target_uid = 2;   // 目标玩家
    uint32 target_home_owner_uid = 3;
    uint32 target_home_gameserver_id = 4;
    uint32 target_home_param = 5;
}

// 包数量信息
message PacketCountInfo {
    uint32 cmd_id = 1;
    uint32 count = 2;
}

// 客户端发包频率超限通知
message PacketFreqencyExceedNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10003;
    }

    uint32 packet_count = 1;                        // 包数量
    uint32 interval = 2;                            // 时间段(毫秒)
    repeated PacketCountInfo packet_count_list = 3; // 每个包的数量
}

// 场景Group批量异步加载
message SceneAsyncLoadGroupBatchNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10090;
    }
}

message CrcVersionConfig {
    repeated string client_version_list = 1;
}

// gameserver往nodeserver同步数值和资源版本
message ClientVersionSyncNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10073;
    }

    DataVersionConfig data_version_config = 1;
    map<uint32, ResVersionConfig> res_version_config_map = 2;
    map<uint32, CrcVersionConfig> crc_version_config_map = 3;
    map<uint32, ResVersionConfig> next_res_version_config_map = 4;
}

// 服务成功返回
message RegisterServiceSuccessNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10099;
    }
}

// 主线程成功加载数值
message ReloadConfigNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10031;
    }
}

message MultiserverServiceTypeNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10075;
    }

    repeated ServiceType service_type_list = 1;
}

message MatchServiceStopNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10048;
    }

    uint32 server_id = 1;
}

message MatchServiceStopImplementNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10097;
    }

    MatchServiceStopNotify msg = 1;
}

message ServerBlockPlayerMpNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10081;
    }

    bool is_unlock = 1;
    uint32 end_time = 2;
}

message ServerBlockPlayerChatNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10005;
    }

    bool is_unlock = 1;
    uint32 end_time = 2;
}

message ServerCheckSegmentCrcNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 10082;
    }
}
