// 战斗协议

syntax = "proto3";

package proto;

import "define.proto";

option go_package = "./;proto";

// 消息的转发类别
enum ForwardType {
    FORWARD_LOCAL = 0;                   // 只是本地
    FORWARD_TO_ALL = 1;                  // 发给所有的客户端
    FORWARD_TO_ALL_EXCEPT_CUR = 2;       // 发给除了自己的客户端
    FORWARD_TO_HOST = 3;                 // 发给主机
    FORWARD_TO_ALL_GUEST = 4;            // 发给所有的客机（除了主机）
    FORWARD_TO_PEER = 5;                 // 发给某个指定的peer，读取固定字段forward_peer
    FORWARD_TO_PEERS = 6;                // 转发给指定的某些PeerId，读取固定字段forward_peer_list
    FORWARD_ONLY_SERVER = 7;             // 只发送给服务器的，不用转发给其他机器
    FORWARD_TO_ALL_EXIST_EXCEPT_CUR = 8; // 转发给除了当前剩下的所有有给定entityid单位的客户端
}

enum HitColliderType {
    HIT_COLLIDER_INVALID = 0;
    HIT_COLLIDER_HIT_BOX = 1;
    HIT_COLLIDER_WET_HIT_BOX = 2;
    HIT_COLLIDER_HEAD_BOX = 3;
}

enum CombatTypeArgument {
    COMBAT_NONE = 0;
    COMBAT_EVT_BEING_HIT = 1;
    COMBAT_ANIMATOR_STATE_CHANGED = 2;
    COMBAT_FACE_TO_DIR = 3;
    COMBAT_SET_ATTACK_TARGET = 4;
    COMBAT_RUSH_MOVE = 5;
    COMBAT_ANIMATOR_PARAMETER_CHANGED = 6;
    ENTITY_MOVE = 7;
    SYNC_ENTITY_POSITION = 8;
    COMBAT_STEER_MOTION_INFO = 9;
    COMBAT_FORCE_SET_POS_INFO = 10;
    COMBAT_COMPENSATE_POS_DIFF = 11;
    COMBAT_MONSTER_DO_BLINK = 12;
    COMBAT_FIXED_RUSH_MOVE = 13;
    COMBAT_SYNC_TRANSFORM = 14;
    COMBAT_LIGHT_CORE_MOVE = 15;
    COMBAT_BEING_HEALED_NTF = 16;
    COMBAT_SKILL_ANCHOR_POSITION_NTF = 17;
    COMBAT_GRAPPLING_HOOK_MOVE = 18;
}

// Hitcollision
message HitCollision {
    HitColliderType hit_collider_type = 8;
    Vector hit_point = 7;
    float attackee_hit_force_angle = 2;
    Vector hit_dir = 13;
    float attackee_hit_entity_angle = 15;
    int32 hit_box_index = 4;
}

// AttackHitEffectResult
message AttackHitEffectResult {
    float hit_halt_time_scale = 8;
    uint32 original_hit_eff_level = 12;
    float air_strength = 15;    // 被击飞的程度
    uint32 hit_eff_level = 2;   // ConfigCombat.h data::HitLevel
    float hit_halt_time = 13;
    float retreat_strength = 7; // 被击退的程度
}

// 用来确定ability的，ability modifier和action的local id索引
message AbilityIdentifier {
    uint32 modifier_owner_id = 2;
    uint32 instanced_modifier_id = 9;
    uint32 instanced_ability_id = 10;
    bool is_serverbuff_modifier = 6;
    uint32 ability_caster_id = 15;
    int32 local_id = 3;
}

// AttackResult，伤害的打包消息 之后Config中的东西会通过animeventid和技能的index来替换掉，减少流量消耗
message AttackResult {
    bool is_resist_text = 1858;             // 客户端纯表现用，是否被抵抗
    uint32 create_count_sync_to_server = 1011;
    uint32 amplify_reaction_type = 2005;
    uint32 endure_break = 7;
    uint32 element_type = 5;
    float element_durability_attenuation = 425;
    uint32 defense_id = 15;
    uint32 attack_timestamp_ms = 1188;
    uint32 bullet_fly_time_ms = 91;
    bool is_crit = 13;
    float element_amplify_rate = 900;       // 某些元素反应会放大本次的最终伤害
    uint32 attack_count = 1564;
    uint32 critical_rand = 1664;            // 暴伤随机数
    uint32 hit_pos_type = 2;
    string anim_event_id = 4;
    AttackHitEffectResult hit_eff_result = 8;
    float damage_shield = 1202;             // 用来计算元素盾伤害，因为Damage很有可能被重置，导致元素盾不正确
    float endure_delta = 430;
    Vector resolved_dir = 1;
    float damage = 6;
    uint32 addhurt_reaction_type = 1887;
    uint32 hashed_anim_event_id = 278;
    bool use_gadget_damage_action = 1418;   // 直接使用gadget trigger action damagebyattackvalue
    int32 hit_retreat_angle_compat = 9;
    AbilityIdentifier ability_identifier = 14;
    uint32 attacker_id = 11;
    bool mute_element_hurt = 1530;          // 是否元素免伤
    uint32 target_type = 1366;
    HitCollision hit_collision = 10;
    uint32 gadget_damage_action_idx = 1110; // 使用的action索引
}

// 单位被击中的消息数据
message EvtBeingHitInfo {
    uint32 peer_id = 6;
    AttackResult attack_result = 7;
    uint32 frame_num = 4;
}

message EvtHittingOtherInfo {
    AttackResult attack_result = 2;
    uint32 peer_id = 8;
}

// 单位被击中的消息，服务器负责转发到所有客户端(Server -> All Client, forward_type == FORWARD_TO_ALL)
message EvtBeingHitNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 372;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 6;
    EvtBeingHitInfo being_hit_info = 3;
}

message EvtAnimatorParameterInfo {
    uint32 entity_id = 4;
    bool is_server_cache = 5;             // 服务器帮忙缓存动画参数
    AnimatorParameterValueInfo value = 7; // 动画值信息
    int32 name_id = 15;                   // 动画名称ID
}

// 动画的同步消息，服务器负责转发到除了当前客户端的其他客户端(Server -> All Client Except Cur, forward_type == FORWARD_TO_ALL_EXCEPT_CUR)
message EvtAnimatorParameterNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 398;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    EvtAnimatorParameterInfo animator_param_info = 12;
    ForwardType forward_type = 14;
}

message AbilityArgument {
    oneof arg {
        uint32 int_arg = 5;
        float float_arg = 15;
        string str_arg = 11;
    }
}

// 主机通知
message HostPlayerNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 312;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 host_peer_id = 13; // 主机PeerID
    uint32 host_uid = 10;     // 主机UID
}

// 单位发起主动技能消息，服务器负责转发到所有客户端(Server -> All Client Except cur, forward_type == FORWARD_TO_ALL_EXCEPT_CUR)
message EvtDoSkillSuccNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 335;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 caster_id = 13;
    ForwardType forward_type = 10;
    // 攻击瞬间强制设置面向
    Vector forward = 15;
    uint32 skill_id = 7;
}

// authority创建动态gaget的请求，服务器负责转发到其他客户端
message EvtCreateGadgetNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 307;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_async_load = 8;
    uint32 camp_type = 5;
    bool sight_group_with_owner = 10;
    repeated uint32 target_entity_id_list = 889;
    ForwardType forward_type = 12;
    uint32 entity_id = 2;
    uint32 target_entity_id = 3;
    uint32 camp_id = 15;
    uint64 guid = 6;
    Vector init_euler_angles = 13;
    uint32 target_lock_point_index = 11;
    repeated uint32 target_lock_point_index_list = 1920;
    Vector init_pos = 4;
    uint32 owner_entity_id = 9;
    uint32 room_id = 7;
    bool is_peer_id_from_player = 25;
    uint32 prop_owner_entity_id = 1;
    bool is_true_life_time_by_owner = 379;
    uint32 config_id = 14;
}

// authority销毁动态gaget的请求
message EvtDestroyGadgetNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 321;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 5;
    uint32 entity_id = 3;
}

// 强制转向指定单位
message EvtFaceToEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 303;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 face_entity_id = 5;
    ForwardType forward_type = 9;
    uint32 entity_id = 1;
}

// 强制转向指定方向
message EvtFaceToDirInfo {
    uint32 entity_id = 12;
    Vector face_dir = 14;
}

// 强制转向指定方向
message EvtFaceToDirNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 390;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 13;
    EvtFaceToDirInfo evt_face_to_dir_info = 5;
}

// authority扣体力的请求
message EvtCostStaminaNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 373;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 skill_id = 6;
    float cost_stamina = 11;
}

message EvtSetAttackTargetInfo {
    uint32 entity_id = 11;
    uint32 select_point_index = 6;
    uint32 attack_target_id = 7;
}

// 同步切换目标
message EvtSetAttackTargetNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 399;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 1;
    EvtSetAttackTargetInfo evt_set_attack_target_info = 11;
}

message EvtAnimatorStateChangedInfo {
    int32 face_angle_compact = 14;
    uint32 to_state_hash = 5;
    uint32 normalized_time_compact = 9;
    uint32 layer = 2;
    Vector pos = 13;
    float fade_duration = 3;
    bool forceSync = 1;
    uint32 entity_id = 15;
    bool handle_animator_state_immediately = 7;
}

message EvtCompensatePosDiffInfo {
    Vector cur_pos = 14;
    uint32 entity_id = 11;
    int32 face_angle_compact = 10;
    uint32 cur_hash = 4;
    uint32 normalized_time_compact = 3;
}

message EvtMonsterDoBlink {
    Vector target_rot = 3;
    Vector target_pos = 7;
    uint32 entity_id = 2;
}

message EvtFixedRushMove {
    uint32 entity_id = 15;
    float speed = 3;
    bool need_set_is_in_air = 7;
    repeated uint32 animator_state_id_list = 2;
    Vector target_pos = 9;
    bool check_animator_state_on_exit_only = 6;
    string override_collider = 13;
}

message EvtSyncTransform {
    uint32 entity_id = 15;
    Vector entity_pos = 6;
    Vector entity_rot = 1;
}

message EvtLightCoreMove {
    Vector target_pos = 15;
    float acelerate = 11;
    uint32 entity_id = 5;
    float max_absorb_time = 10;
    float speed = 14;
}

message EvtGrapplingHookMove {
    float acceleration = 1;
    repeated uint32 animator_state_id_list = 2;
    uint32 entity_id = 3;
    bool need_set_is_in_air = 13;
    float speed = 12;
    float max_speed = 8;
    bool check_animator_state_on_exit_only = 11;
    string override_collider = 14;
    Vector target_pos = 10;
}

// 动画的同步消息，服务器负责转发到除了当前客户端的其他客户端(Server -> All Client Except Cur, forward_type == FORWARD_TO_ALL_EXCEPT_CUR)
message EvtAnimatorStateChangedNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 331;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 3;
    EvtAnimatorStateChangedInfo evt_animator_state_changed_info = 10;
}

message EvtRushMoveInfo {
    int32 state_name_hash = 11;        // 为了校验本次rushmove
    Vector rush_to_pos = 9;            // rush to point
    Vector rush_attack_target_pos = 8; // rush attack target pos
    uint32 entity_id = 4;
    float timeRange = 15;
    Vector velocity = 6;
    Vector pos = 2;                    // entity rush move start pos
    int32 face_angle_compact = 10;     // entity rush move start face angle
}

message EvtMotionInfoDuringSteerAttack {
    Vector face_dir = 4;
    Vector velocity = 3;
    Vector pos = 1;
    uint32 entity_id = 6;
}

message EvtCombatSteerMotionInfo {
    Vector pos = 12;
    Vector velocity = 10;
    uint32 entity_id = 4;
    Vector face_dir = 1;
}

message EvtCombatForceSetPosInfo {
    uint32 ice_id = 9;
    uint32 collider_entity_id = 10;
    uint32 entity_id = 6;
    Vector target_pos = 1;
}

message EvtSyncEntityPositionInfo {
    uint32 entity_id = 10;
    uint32 normalized_time_compact = 13;
    uint32 state_hash = 8;
    int32 face_angle_compact = 7;
    Vector pos = 15;
}

// rushMove 同步消息
message EvtRushMoveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 375;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 1;
    EvtRushMoveInfo evt_rush_move_info = 15;
}

// 子弹独有的命中的消息
message EvtBulletHitNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 348;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 single_bullet_id = 8;
    Vector hit_point = 15;
    Vector hit_normal = 11;
    int32 hit_box_index = 9;
    uint32 hit_entity_id = 3;
    uint32 entity_id = 5;
    uint32 forward_peer = 7;
    ForwardType forward_type = 2;
    HitColliderType hit_collider_type = 6;
}

// 子弹独有的隐藏的消息
message EvtBulletDeactiveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 397;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 6;
    uint32 entity_id = 9;
    Vector disappear_pos = 4;
}

// entity开始dieend的消息，用来remote那边的startend和authority同步，否则会出现比如安伯的娃娃authority那边dieend，但是remote timer计时没到，就没有dieend，但是又做了技能的action了，看起来不同步
message EvtEntityStartDieEndNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 381;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool immediately = 15;
    uint32 die_state_flag = 12;
    uint32 entity_id = 8;
    ForwardType forward_type = 11;
}

// 子弹移动同步消息
message EvtBulletMoveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 365;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 14;
    Vector cur_pos = 1; // 当前位置
    uint32 entity_id = 11;
}

// 进入瞄准模式
message EvtAvatarEnterFocusNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 304;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 1;
    bool can_move = 10;
    bool enter_holding_focus_shoot = 13;
    bool disable_aim_layer = 6;
    bool use_auto_focus = 5;
    bool fast_focus = 3;
    bool show_cross_hair = 12;
    bool enter_normal_focus_shoot = 14;
    ForwardType forward_type = 8;
    Vector focus_forward = 7;
    bool disable_anim = 9;
    bool use_focus_sticky = 15;
    bool use_gyro = 11;
}

// 退出瞄准模式
message EvtAvatarExitFocusNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 393;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    Vector finish_forward = 12;
    ForwardType forward_type = 11;
    uint32 entity_id = 14;
}

// 瞄准模式中定期更新瞄准信息，比如瞄准的单位，摇杆相关参数等
message EvtAvatarUpdateFocusNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 327;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 7;
    Vector focus_forward = 11;
    uint32 entity_id = 10;
}

message AuthorityChange {
    EntityAuthorityInfo entity_authority_info = 5;
    uint32 authority_peer_id = 3;
    uint32 entity_id = 13;
}

// 实体的Authority切换通知(S->C)
message EntityAuthorityChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 394;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated AuthorityChange authority_change_list = 15;
}

// 服务器AvatarBuff添加通知
message AvatarBuffAddNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 388;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint64 avatar_guid = 10; // Avatar Guid
    uint32 buff_id = 6;      // Buff ID
}

// 服务器AvatarBuff删除通知
message AvatarBuffDelNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 326;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint64 avatar_guid = 10; // Avatar Guid
    uint32 buff_id = 12;     // Buff ID
}

// 角色进入或退出战斗状态上报服务器(C->S)
// 怪物被杀死或角色离开场景时不用上报
message MonsterAlertChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 363;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 avatar_entity_id = 15;            // 角色entity_id
    repeated uint32 monster_entity_list = 5; // 多个怪物同时入战
    uint32 is_alert = 13;                    // 是否变为alert
}

// 服务器脚本设置客户端怪物入战或脱战（S->C）
// 客户端的怪物因为这个协议而改变状态的话也需要上报服务器
message MonsterForceAlertNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 395;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 monster_entity_id = 13; // 怪物的entity_id
}

// 角色进入元素视野上报服务器(C->S)
message AvatarEnterElementViewNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 334;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_triggerd = 3;         // true:开启元素视野 false:关闭元素视野
    uint32 avatar_entity_id = 12; // 角色entity_id
}

// 创建Gadget到equippart上(S->C)
message TriggerCreateGadgetToEquipPartNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 350;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 gadget_id = 1;         // equip的gadget_id
    uint32 entity_id = 13;        // owner的entity_id
    string equip_part = 14;       // owner的equip_part
    uint32 gadget_entity_id = 10; // gadget的entity_id
}

// Entity的哪些部件(Transform)被隐藏，服务器负责转发到除了当前客户端的其他客户端(Server -> All Client Except Cur, forward_type == FORWARD_TO_ALL_EXCEPT_CUR)
message EvtEntityRenderersChangedNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 343;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 8;
    bool is_server_cache = 3;                            // 服务器帮忙缓存 Entity Renderers
    EntityRendererChangedInfo renderer_changed_info = 5; // Entity Renderers的名称列表
    uint32 entity_id = 15;
}

// Animator的ForceSetAirMove通知，服务器负责转发到除了当前客户端的其他客户端(Server -> All Client Except Cur, forward_type == FORWARD_TO_ALL_EXCEPT_CUR)
message AnimatorForceSetAirMoveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 374;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 14;
    bool in_air_move = 13;
    ForwardType forward_type = 9;
}

// AI的CD时间
message AiSkillCdInfo {
    map<uint32, uint32> skill_cd_map = 11; // CD时间(key:skill_id)
    map<uint32, uint32> skill_group_cd_map = 6;
}

// 同步AI的CD时间通知(C->S)
message EvtAiSyncSkillCdNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 376;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    map<uint32, AiSkillCdInfo> ai_cd_map = 7; // AI的CD时间(key:entity_id)
}

// EvtBegingHit合包，服务器负责转发到所有客户端(Server -> All Client, forward_type == FORWARD_TO_ALL)
message EvtBeingHitsCombineNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 346;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    ForwardType forward_type = 11;
    repeated EvtBeingHitInfo evt_being_hit_info_list = 7;
}

// 同步角色坐下
message EvtAvatarSitDownNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 324;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    Vector position = 9;
    uint32 entity_id = 4;
    uint64 chair_id = 6;
}

// 同步角色站起
message EvtAvatarStandUpNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 356;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint64 chair_id = 11;
    int32 performID = 6;
    int32 direction = 1;
    uint32 entity_id = 9;
}

// 客户端发起创建MassiveEntity的请求
message CreateMassiveEntityReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 342;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated ClientMassiveEntity massive_entity_list = 1;
}

message CreateMassiveEntityRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 330;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 1;
}

// 服务器创建MassiveEntity转发给所有的客户端
message CreateMassiveEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 367;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ServerMassiveEntity massive_entity_list = 15;
}

// 删除MassiveEntity的通知，服务器
message DestroyMassiveEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 358;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated ClientMassiveEntity massive_entity_list = 7;
}

// MassiveEntity的元素反应状态变化同步，只在authority上做，同步给remote
message MassiveEntityStateChangedNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 370;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated MassiveEntityState massive_entity_state_list = 4;
}

message TeamEntityInfo {
    uint32 authority_peer_id = 10;
    AbilitySyncStateInfo team_ability_info = 9;
    uint32 team_entity_id = 8;
}

// 全量更新
message SyncTeamEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 317;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_id = 13;
    repeated TeamEntityInfo team_entity_info_list = 15;
}

message DelTeamEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 302;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 del_entity_id_list = 15;
    uint32 scene_id = 8;
}

message EvtSyncSkillAnchorPosition {
    uint32 entity_id = 2;
    Vector skill_anchor_position = 13;
}

message CombatInvokeEntry {
    bytes combat_data = 12;
    ForwardType forward_type = 10;
    CombatTypeArgument argument_type = 11;
}

message CombatInvocationsNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 319;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated CombatInvokeEntry invoke_list = 14;
}

// ServerBuff增减通知
message ServerBuffChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 361;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum ServerBuffChangeType {
        ADD_SERVER_BUFF = 0;
        DEL_SERVER_BUFF = 1;
    }

    ServerBuffChangeType server_buff_change_type = 7; // 增加还是删除
    bool is_creature_buff = 10;
    repeated uint32 entity_id_list = 1;
    repeated uint64 avatar_guid_list = 12;            // 哪些avatar
    repeated ServerBuff server_buff_list = 11;        // 哪些server_buff
}

// 客户端同步AI仇恨
message AiThreatInfo {
    map<uint32, uint32> ai_threat_map = 11; // key:仇恨对象EntityID，value:仇恨值
}

message EvtAiSyncCombatThreatInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 329;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    map<uint32, AiThreatInfo> combat_threat_info_map = 8; // key:AI的EntityID
}

message MassiveEntityElementOpBatchNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 357;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    int32 entity_type = 6;
    uint32 op_idx = 9;
    uint32 user_id = 11;
    uint32 attacker_id = 3;
    int32 source_element_type = 12;
    int32 reaction_source_type = 4;
    float attack_element_durability = 7;
    oneof check_shape {
        ShapeSphere shape_sphere = 10;
        ShapeBox shape_box = 2;
    }
}

message AiSyncInfo {
    uint32 entity_id = 9;
    bool is_self_killing = 8;
    bool has_path_to_target = 4;
}

message EntityAiSyncNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 400;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 local_avatar_alerted_monster_list = 15;
    repeated AiSyncInfo info_list = 1;
}

message LuaSetOptionNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 316;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum LuaOptionType {
        LUA_OPTION_NONE = 0;
        LUA_OPTION_PLAYER_INPUT = 1;
    }

    string lua_set_param = 8;
    LuaOptionType option_type = 10;
}

message EvtDestroyServerGadgetNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 387;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 7;
}

message EntityAiKillSelfNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 340;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 12;
}

message EvtAvatarLockChairReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 318;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint64 chair_id = 5;
    Vector position = 8;
}

message EvtAvatarLockChairRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 366;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint64 chair_id = 14;
    uint32 entity_id = 15;
    Vector position = 4;
    int32 retcode = 12;
}

message ReportFightAntiCheatNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 368;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 cheat_count = 8;
    uint32 cheat_type = 12;
}

message EvtBeingHealedNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 333;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 target_id = 1;
    float real_heal_amount = 5;
    uint32 source_id = 13;
    float heal_amount = 4;
}

message EvtLocalGadgetOwnerLeaveSceneNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 384;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 10;
}
