// 邮件协议

syntax = "proto3";

package proto;

import "define.proto";

option go_package = "./;proto";

enum AuthkeySignType {
    AUTHKEY_SIGN_TYPE_NONE = 0;
    AUTHKEY_SIGN_TYPE_DEFAULT = 1;
    AUTHKEY_SIGN_TYPE_RSA = 2;
}

// 新邮件/邮件数据变化/删除邮件时通知 S->C
message MailChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1498;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated MailData mail_list = 14;     // 增加或字段变化的邮件
    repeated uint32 del_mail_id_list = 8; // 删除的邮件
}

// 读邮件通知服务端 C->S
message ReadMailNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1412;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 mail_id_list = 2;
}

// 获取邮件附件
message GetMailItemReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1435;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 mail_id_list = 6;
}

message GetMailItemRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1407;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 7;
    repeated uint32 mail_id_list = 3;
    repeated EquipParam item_list = 2; // 获得的道具
}

// 删除邮件
message DelMailReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1421;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 mail_id_list = 12;
}

message DelMailRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1403;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 11;
    repeated uint32 mail_id_list = 5;
}

// 加密信息获取
message GetAuthkeyReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1490;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    string auth_appid = 14;  // appid
    uint32 sign_type = 7;    // 加密类型
    uint32 authkey_ver = 13; // 密钥版本
}

message GetAuthkeyRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1473;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string auth_appid = 4;  // appid
    uint32 sign_type = 15;  // 加密类型
    int32 retcode = 6;
    uint32 authkey_ver = 9; // 密钥版本
    string game_biz = 11;   // 运营要求的game_biz
    string authkey = 3;     // 加密串
}

// 通知是否有新邮件，登录时通知 S->C
message ClientNewMailNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1499;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 not_read_num = 7;           // 未读邮件数量
    uint32 not_got_attachment_num = 2; // 未领取的邮件的数量
}

// 请求拉取所有邮件数据 C->S
message GetAllMailReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1431;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_collected = 7;
}

// 请求拉取所有邮件数据的回复 S->C
message GetAllMailRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1475;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 8;
    repeated MailData mail_list = 14; // 所有邮件的列表
    bool is_collected = 1;
    bool is_truncated = 2;
}

message ChangeMailStarNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1448;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_star = 14;
    repeated uint32 mail_id_list = 2;
}

message GetAllMailNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1497;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_collected = 13;
}

message GetAllMailResultNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1481;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string transaction = 9;
    repeated MailData mail_list = 5;
    uint32 page_index = 11;
    uint32 total_page_count = 4;
    bool is_collected = 7;
    int32 retcode = 14;
}
