// 调查相关协议

syntax = "proto3";

package proto;

import "define.proto";

option go_package = "./;proto";

message Investigation {
    enum State {
        INVALID = 0;      // 非法
        IN_PROGRESS = 1;  // 进行中
        COMPLETE = 2;     // 已完成
        REWARD_TAKEN = 3; // 已领奖
    }

    uint32 total_progress = 5; // 总进度
    State state = 2;           // 调查当前的状态
    uint32 progress = 13;      // 调查当前进度
    uint32 id = 9;             // 调查ID
}

message InvestigationTarget {
    enum State {
        INVALID = 0;      // 非法
        IN_PROGRESS = 1;  // 进行中
        COMPLETE = 2;     // 已完成
        REWARD_TAKEN = 3; // 已领奖
    }

    uint32 quest_id = 15;        // 对应的子任务ID
    State state = 2;             // 当前的状态
    uint32 progress = 8;
    uint32 total_progress = 7;
    uint32 investigation_id = 3; // 对应的调查ID
}

message PlayerInvestigationAllInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1928;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated Investigation investigation_list = 15;
    repeated InvestigationTarget investigation_target_list = 12;
}

// 领取调查的奖励
message TakeInvestigationRewardReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1912;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 id = 5; // 要领取奖励的调查ID
}

message TakeInvestigationRewardRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1922;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
    uint32 id = 12; // 领取奖励的调查ID
}

// 领取调查目标任务的奖励
message TakeInvestigationTargetRewardReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1918;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 quest_id = 11; // 要领取奖励的调查任务ID
}

message TakeInvestigationTargetRewardRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1916;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 1;
    uint32 quest_id = 2; // 领取奖励的调查任务ID
}

// 拉取调查怪物的信息
message GetInvestigationMonsterReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1901;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 city_id_list = 3; // 请求查询的city_id列表
    bool is_for_mark = 4;
}

message InvestigationMonster {
    enum LockState {
        LOCK_NONE = 0;  // 无锁定
        LOCK_QUEST = 1; // 任务锁定
    }

    bool is_alive = 9;             // 怪物是否活着
    uint32 refresh_interval = 3;   // 总共刷新需要的时间间隔
    uint32 id = 13;                // 配置ID
    uint32 level = 5;              // 怪物等级
    uint32 boss_chest_num = 1;     // 已经领取的boss宝箱数量
    WeeklyBossResinDiscountInfo weekly_boss_resin_discount_info = 12;
    uint32 monster_id = 301;
    Vector pos = 14;               // 位置
    uint32 resin = 8;
    uint32 max_boss_chest_num = 4; // boss宝箱领取数量限制
    uint32 next_refresh_time = 11; // 下次刷新时间戳
    uint32 group_id = 285;
    uint32 scene_id = 10;
    bool is_area_locked = 15;
    LockState lock_state = 2;      // 锁定状态，展示用
    uint32 next_boss_chest_refresh_time = 7;
    uint32 city_id = 6;            // 所属城市ID
}

message GetInvestigationMonsterRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1910;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated InvestigationMonster monster_list = 10;
    int32 retcode = 1;
    bool is_for_mark = 2;
}

message PlayerInvestigationNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1911;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated Investigation investigation_list = 1;
}

message PlayerInvestigationTargetNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1929;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated InvestigationTarget investigation_target_list = 1;
}

message MarkTargetInvestigationMonsterNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1915;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 11;
    uint32 monster_id = 4;
    uint32 group_id = 5;
    uint32 investigation_monster_id = 12;
}

message InvestigationMonsterUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1906;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    InvestigationMonster investigation_monster = 5;
}

message InvestigationQuestDailyNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1921;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }
}

message InvestigationReadQuestDailyNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 1902;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}
