// 场景相关协议

syntax = "proto3";

package proto;

import "cmd/cmd_widget.proto";
import "define.proto";

option go_package = "./;proto";

enum EnterType {
    ENTER_NONE = 0;
    ENTER_SELF = 1;           // 进入自己的场景
    ENTER_GOTO = 2;           // 跳点
    ENTER_JUMP = 3;           // 跳场景(自己的场景)
    ENTER_OTHER = 4;          // 进入别人的场景
    ENTER_BACK = 5;           // 返回自己的场景
    ENTER_DUNGEON = 6;        // 进入副本
    ENTER_DUNGEON_REPLAY = 7; // 在副本中选择重玩
    ENTER_GOTO_BY_PORTAL = 8; // 玩家在场景内通过传送门跳点(主要用于客户端)
    ENTER_SELF_HOME = 9;
    ENTER_OTHER_HOME = 10;
    ENTER_GOTO_RECREATE = 11;
}

enum VisionType {
    VISION_NONE = 0;
    VISION_MEET = 1;            // 出现(进入视野)
    VISION_REBORN = 2;          // 重生
    VISION_REPLACE = 3;         // 主动更换
    VISION_WAYPOINT_REBORN = 4; // 副本路点重生
    VISION_MISS = 5;            // 消失(离开视野)
    VISION_DIE = 6;             // 死亡
    VISION_GATHER_ESCAPE = 7;   // 目前只用于环境小动物采集时逃走
    VISION_REFRESH = 8;         // group刷新导致物件消失(TODO...暂且不会发给客户端)
    VISION_TRANSPORT = 9;       // 在同一个场景内传送
    VISION_REPLACE_DIE = 10;    // 客户端需要区分死亡换人和主动换人
    VISION_REPLACE_NO_NOTIFY = 11;
    VISION_BORN = 12;
    VISION_PICKUP = 13;
    VISION_REMOVE = 14;
    VISION_CHANGE_COSTUME = 15;
    VISION_FISH_REFRESH = 16;
    VISION_FISH_BIG_SHOCK = 17;
    VISION_FISH_QTE_SUCC = 18;
    VISION_CAPTURE_DISAPPEAR = 19;
}

// 创建原因
enum CreateReason {
    CREATE_NONE = 0;
    CREATE_QUEST = 1;
    CREATE_ENERGY = 2;
}

// 传送原因
enum TransmitReason {
    TRANSMIT_NONE = 0;
    TRANSMIT_QUEST = 1; // 任务
}

enum SealBattleType {
    SEAL_BATTLE_KEEP_ALIVE = 0;
    SEAL_BATTLE_KILL_MONSTER = 1;
    SEAL_BATTLE_ENERGY_CHARGE = 2;
}

enum DungeonEntryBlockReason {
    DUNGEON_ENTRY_REASON_NONE = 0;
    DUNGEON_ENTRY_REASON_LEVEL = 1;
    DUNGEON_ENTRY_REASON_QUEST = 2;
    DUNGEON_ENTRY_REASON_MULIPLE = 3;
}

enum AreaPlayType {
    AREA_PLAY_NONE = 0;
    AREA_PLAY_CLIMATE = 1;
    AREA_PLAY_REGIONAL_PLAY = 2;
}

message PlayerEnterSceneNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 272;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 prev_scene_id = 6;     // 进入之前的场景ID
    uint32 dungeon_id = 12;       // 进入大世界时为0
    bool is_skip_ui = 1732;
    uint32 scene_id = 15;         // 场景ID
    EnterType type = 13;          // 进入类型
    uint64 scene_begin_time = 14; // 场景开始的时间(1970.1.1到现在的毫秒数)
    uint32 world_level = 11;      // 大世界等级, 如果是dungeon该字段无效
    uint32 world_type = 1490;
    uint32 target_uid = 4;        // 场景所属的玩家ID
    bool is_first_login_enter_scene = 3;
    repeated uint32 scene_tag_id_list = 5;
    string scene_transaction = 1842;
    Vector prev_pos = 8;          // 进入之前的位置
    uint32 enter_reason = 1828;
    Vector pos = 7;               // 位置
    uint32 enter_scene_token = 2; // 进场token，用于区分不同的进场流程
}

// 退出当前场景
message LeaveSceneReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 298;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message LeaveSceneRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 212;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 3;
}

// C->S场景初始化完成
message SceneInitFinishReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 235;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 enter_scene_token = 11; // 进场token
}

message SceneInitFinishRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 207;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    int32 retcode = 13;
    uint32 enter_scene_token = 8;
}

// 地图上的实体出现通知
message SceneEntityAppearNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 221;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    VisionType appear_type = 15;              // 出现类型
    uint32 param = 9;                         // 出现参数
    repeated SceneEntityInfo entity_list = 5; // 实体列表
}

// 地图上的实体消失通知
message SceneEntityDisappearNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 203;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 param = 6;
    repeated uint32 entity_list = 1; // 实体ID列表
    VisionType disappear_type = 2;   // 消失类型
}

// 地图上的实体移动请求
message SceneEntityMoveReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 290;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 0;
        IS_ALLOW_CLIENT = 1;
    }

    MotionInfo motion_info = 7; // 运动信息
    uint32 scene_time = 4;      // 地图时间
    uint32 entity_id = 8;       // 实体ID
    uint32 reliable_seq = 15;   // 可靠包的序列号(对于不可靠包，则为上一个可靠包的序列号)
}

message SceneEntityMoveRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 273;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 4;       // 实体ID
    MotionInfo fail_motion = 1; // 失败时的运动信息
    uint32 scene_time = 10;     // 失败时的地图时间
    uint32 reliable_seq = 6;    // 失败时的序列号
    int32 retcode = 8;
}

// 地图上的角色消耗体力移动请求
message SceneAvatarStaminaStepReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 299;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool use_client_rot = 15; // 是否使用客户端朝向
    Vector rot = 7;
}

message SceneAvatarStaminaStepRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 231;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
    }

    bool use_client_rot = 9;
    int32 retcode = 7;
    Vector rot = 11;
}

// 地图上的实体移动通知(S->C)
message SceneEntityMoveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 275;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
    }

    MotionInfo motion_info = 6; // 运动信息
    uint32 entity_id = 8;       // 实体ID
    uint32 scene_time = 15;     // 地图时间
    uint32 reliable_seq = 2;    // 可靠包的序列号(对于不可靠包，则为上一个可靠包的序列号)
}

message VehicleLocationInfo {
    Vector rot = 14;
    uint32 entity_id = 15;
    float cur_hp = 11;
    uint32 owner_uid = 5;
    Vector pos = 1;
    repeated uint32 uid_list = 3;
    uint32 gadget_id = 13;
    float max_hp = 6;
}

message ScenePlayerLocationNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 248;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
    }

    repeated VehicleLocationInfo vehicle_loc_list = 3;
    uint32 scene_id = 9;
    repeated PlayerLocationInfo player_loc_list = 14; // 所有玩家的位置信息
}

// 请求地图上的已经解锁的传送点、地下城入口信息，不包含默认解锁的
message GetScenePointReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 297;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 belong_uid = 10; // 所属的玩家ID
    uint32 scene_id = 4;    // 场景ID
}

message CityInfo {
    uint32 city_id = 15;
    uint32 crystal_num = 3;
    uint32 level = 4;
}

message GetScenePointRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 281;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 not_explored_dungeon_entry_list = 11;  // 未被探索解锁的地城入口config ID列表
    repeated uint32 to_be_explore_dungeon_entry_list = 15; // 待探索地城入口config ID列表
    repeated uint32 locked_point_list = 2;                 // 已锁的传送点列表
    repeated uint32 unhide_point_list = 5;
    int32 retcode = 9;
    uint32 belong_uid = 12;                                // 所属的玩家ID
    repeated uint32 unlocked_point_list = 13;              // 所有已解锁传送点列表
    repeated uint32 unlock_area_list = 1;                  // 已解锁的一级区域
    repeated uint32 hide_point_list = 4;
    uint32 scene_id = 14;                                  // 场景ID
    repeated uint32 not_interact_dungeon_entry_list = 6;
    repeated uint32 group_unlimit_point_list = 10;         // group未解锁的点列表
}

// 进入传送点区域通知(C->S), 女神像传送点
message EnterTransPointRegionNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 205;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 8; // 地图ID
    uint32 point_id = 6; // 传送点ID
}

// 离开传送点区域通知(C->S), 女神像传送点
message ExitTransPointRegionNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 282;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 point_id = 1; // 传送点ID
    uint32 scene_id = 7; // 地图ID
}

// 解锁传送点、地下城入口通知(S->C，解锁传送点以此协议为准)
message ScenePointUnlockNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 247;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 point_list = 13;       // 新增的已解锁传送点列表
    uint32 scene_id = 6;                   // 地图ID
    repeated uint32 unhide_point_list = 12;
    repeated uint32 hide_point_list = 1;
    repeated uint32 locked_point_list = 8; // 新增的被关闭的传送点列表
}

// 传送到目的点
message SceneTransToPointReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 239;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 13; // 地图ID
    uint32 point_id = 1;  // 目的传送点ID
}

message SceneTransToPointRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 253;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 point_id = 14; // 目的传送点ID
    uint32 scene_id = 3;  // 地图ID
    int32 retcode = 8;
}

// 地图上的实体跳点通知
message EntityJumpNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 222;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    // 跳点类型
    enum Type {
        NULL = 0;
        ACTIVE = 1;  // 主动跳点
        PASSIVE = 2; // 被动跳点
    }

    Type jump_type = 9; // 跳点类型
    Vector rot = 8;     // 目的朝向
    Vector pos = 10;    // 目的位置
    uint32 entity_id = 12;
}

// 请求地图上的区域信息
message GetSceneAreaReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 265;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 4;   // 地图ID
    uint32 belong_uid = 7; // 所属的玩家ID
}

message GetSceneAreaRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 204;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 7;
    repeated CityInfo city_info_list = 13; // 城市信息
    uint32 scene_id = 15;                  // 地图ID
    repeated uint32 area_id_list = 9;      // 已解锁区域列表
}

// 地图上的区域解锁通知(S->C)
message SceneAreaUnlockNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 293;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 area_list = 10; // 新增的已解锁区域列表
    uint32 scene_id = 9;            // 地图ID
}

// 地图上的实体淹死
message SceneEntityDrownReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 227;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 10; // 实体ID
}

message SceneEntityDrownRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 294;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 8;
    uint32 entity_id = 11; // 实体ID
}

// 在地图上创建实体
message SceneCreateEntityReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 288;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    CreateEntityInfo entity = 1;
    bool is_destroy_when_disconnect = 10; // 是否断线时销毁
    CreateReason reason = 3;              // 创建原因
}

message SceneCreateEntityRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 226;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 14;
    uint32 entity_id = 1; // 创建的实体ID
    CreateEntityInfo entity = 10;
}

// 在地图上销毁实体
message SceneDestroyEntityReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 263;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 7; // 删除的实体ID
}

message SceneDestroyEntityRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 295;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 14;
    uint32 entity_id = 7; // 删除的实体ID
}

// 地图上的力场解锁通知(S->C)
message SceneForceUnlockNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 206;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_add = 10;                  // 是否为增加
    repeated uint32 force_id_list = 2; // 解锁的力场列表
}

// 地图上的力场锁住通知(S->C)
message SceneForceLockNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 234;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 force_id_list = 9; // 锁住的力场列表
}

// 进入区域请求
message EnterWorldAreaReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 250;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 area_type = 8; // 对应xml中的WorldAreaType
    uint32 area_id = 1;   // 传送点ID
}

message EnterWorldAreaRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 243;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 area_type = 1; // 对应xml中的WorldAreaType
    uint32 area_id = 7;   // 传送点ID
    int32 retcode = 9;
}

// 强制同步实体的状态，任务使用
message EntityForceSyncReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 274;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 room_id = 1;          // 房间编号
    MotionInfo motion_info = 11; // 运动信息
    uint32 entity_id = 13;       // 实体ID
    uint32 scene_time = 12;      // 地图时间
}

message EntityForceSyncRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 276;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_time = 14;     // 失败时的地图时间
    uint32 entity_id = 6;       // 实体ID
    MotionInfo fail_motion = 8; // 失败时的运动信息
    int32 retcode = 4;
}

message GetAreaExplorePointReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 241;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 area_id_list = 14;
}

message GetAreaExplorePointRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 249;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 8;
    repeated uint32 area_id_list = 11;
    repeated uint32 explore_point_list = 4;
}

// 客户端传送请求
message ClientTransmitReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 291;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 2;
    TransmitReason reason = 14; // 原因
    Vector pos = 1;             // 位置
    Vector rot = 9;             // 朝向
}

message ClientTransmitRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 224;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    TransmitReason reason = 3; // 原因
    int32 retcode = 9;
}

// 进入天气区域通知(C->S)
message EnterSceneWeatherAreaNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 256;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 weather_gadget_id = 13; // 天气区域物件ID
}

// 离开天气区域通知(C->S)
message ExitSceneWeatherAreaNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 242;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 weather_gadget_id = 2; // 天气区域物件ID
}

// 区域天气通知(S->C)
message SceneAreaWeatherNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 230;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 weather_area_id = 1;                 // 天气区域ID
    uint32 weather_gadget_id = 9;               // 天气区域物件ID
    uint32 climate_type = 14;                   // 天气类型（data::ClimateType）
    float trans_duration = 15;
    map<uint32, string> weather_value_map = 10; // 不同来源的天气值
}

// 场景中玩家的信息
message ScenePlayerInfo {
    uint32 scene_id = 10;                     // 场景id
    uint32 peer_id = 6;                       // PeerID
    OnlinePlayerInfo online_player_info = 13; // 玩家在线数据
    bool is_connected = 2;                    // 是否离线
    string name = 15;                         // 名字
    uint32 uid = 8;                           // UID
}

// 玩家切换Scene时的广播信息(S->C)
message ScenePlayerInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 267;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ScenePlayerInfo player_info_list = 5;
}

// 玩家的位置信息
message PlayerLocationInfo {
    uint32 uid = 15; // UID
    Vector pos = 3;  // 位置
    Vector rot = 13; // 朝向
}

message PlayerWorldLocationInfo {
    uint32 scene_id = 1;
    PlayerLocationInfo player_loc = 12;
}

// 大世界中玩家的位置通知(S->C)
message WorldPlayerLocationNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 258;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated PlayerWorldLocationInfo player_world_loc_list = 8;
    repeated PlayerLocationInfo player_loc_list = 15; // 所有玩家的位置信息
}

// 通知客户端镜头注目某个点
message BeginCameraSceneLookNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 270;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum KeepRotType {
        KEEP_ROT_X = 0;
        KEEP_ROT_XY = 1;
    }

    uint32 blend_type = 1154;
    float custom_radius = 7;
    bool is_set_screenXY = 5;
    Vector look_pos = 4; // 需要注目的点
    bool is_recover_keep_current = 11;
    bool is_abs_follow_pos = 1375;
    KeepRotType keep_rot_type = 6;
    bool is_change_play_mode = 9;
    uint32 disable_protect = 1103;
    float screen_y = 15;
    bool is_set_follow_pos = 13;
    bool is_force = 12;
    float blend_duration = 1758;
    uint32 entity_id = 1327;
    float screen_x = 3;
    bool is_force_walk = 10;
    repeated string other_params = 1;
    Vector follow_pos = 8;
    bool is_allow_input = 2;
    float duration = 14; // 持续时间
}

// 通知客户端结束镜头注目
message EndCameraSceneLookNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 217;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }
}

// 服务端创建实体，通知客户端在小地图上标识出来
message MarkEntityInMinMapNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 202;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    Vector position = 4;
    uint32 monster_id = 7; // 怪物ID
    uint32 entity_id = 14; // 创建的实体ID
}

// 取消小地图的怪物标记
message UnmarkEntityInMinMapNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 219;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 8; // 创建的实体ID
}

// 客户端请求触发SourceEntityId相关的group trigger, 服务端会限制频率
message ExecuteGroupTriggerReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 257;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    string source_name = 15;      // 源名称
    uint32 target_entity_id = 12; // 目标实体ID
    int32 param2 = 8;             // 参数2
    uint32 source_entity_id = 4;  // 源实体ID, 这个entity必须存在
    int32 param3 = 10;            // 参数3
    int32 param1 = 9;             // 参数1
}

message ExecuteGroupTriggerRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 300;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 13;
}

// 客户端请求升级城市--充能
message LevelupCityReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 216;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 5;
    uint32 area_id = 3;   // 通过哪个女神像
    uint32 item_num = 14; // 玩家充能使用的结晶
}

message LevelupCityRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 287;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 area_id = 9; // 通过哪个女神像
    int32 retcode = 3;
    uint32 scene_id = 4;
    CityInfo city_info = 6;
}

// 路径点改变信息
message RoutePointChangeInfo {
    float wait_time = 6;        // 停留时间
    float target_velocity = 14; // 目标速度
    uint32 point_index = 11;    // 路径点索引
}

// 移动路径改变信息
message SceneRouteChangeInfo {
    bool is_forward = 12;                         // 是否为正向
    uint32 route_id = 15;                         // 路径ID
    uint32 type = 4;                              // 路径类型(取值范围：TrailType)
    repeated RoutePointChangeInfo point_list = 1; // 点改变信息
}

// 场景移动路径改变通知
message SceneRouteChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 240;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_id = 12;                         // 场景ID
    uint32 scene_time = 11;                       // 场景时间(毫秒)
    repeated SceneRouteChangeInfo route_list = 2; // 路径改变信息
}

// 移动平台开始路径移动通知
message PlatformStartRouteNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 218;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    PlatformInfo platform = 15; // 移动平台信息
    uint32 scene_time = 12;     // 场景时间(毫秒)
    uint32 entity_id = 8;       // 移动平台实体ID
}

// 移动平台停止路径移动通知
message PlatformStopRouteNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 266;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_time = 9; // 场景时间(毫秒)
    uint32 entity_id = 12; // 移动平台实体ID
    PlatformInfo platform = 8;
}

// 移动平台改变路径通知
message PlatformChangeRouteNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 268;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 2;      // 移动平台实体ID
    PlatformInfo platform = 1; // 移动平台信息
    uint32 scene_time = 8;
}

// 播放音效通知
message ScenePlayerSoundNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 233;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum PlaySoundType {
        PLAY_SOUND_NONE = 0;
        PLAY_SOUND_START = 1;
        PLAY_SOUND_STOP = 2;
    }

    string sound_name = 4;       // 音效名字
    PlaySoundType play_type = 8; // 播放类型
    Vector play_pos = 3;         // 播放位置
}

// 通过PersonalSceneJumpPoint在大世界、房间场景中切换场景
message PersonalSceneJumpReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 284;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 point_id = 4;
}

message PersonalSceneJumpRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 280;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 dest_scene_id = 5;
    int32 retcode = 8;
    Vector dest_pos = 11;
}

// 封印战斗开始通知
message SealBattleBeginNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 289;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 seal_max_progress = 9; // 最大进度
    uint32 seal_entity_id = 1;    // SealGadget entity id
    uint32 seal_radius = 12;      // 圈半径
    SealBattleType battle_type = 14;
}

// 封印战斗结束通知
message SealBattleEndNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 259;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_win = 4;            // 是否胜利
    uint32 seal_entity_id = 15; // SealGadget entity id
}

// 封印战斗进度同步
message SealBattleProgressNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 232;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 seal_entity_id = 9; // SealGadget entity id
    uint32 max_progress = 10;  // 最大进度
    uint32 seal_radius = 4;    // 圈半径
    uint32 progress = 5;       // 当前进度
    uint32 end_time = 2;       // 结束时间
}

// 客户端打开或关闭道具/角色等会暂停时间的界面时通知服务器
message ClientPauseNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 260;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_open = 1; // 是否是打开界面
}

// 角色进入场景时的数据
message AvatarEnterSceneInfo {
    repeated ServerBuff server_buff_list = 14;     // ServerBuff列表
    uint32 avatar_entity_id = 7;                   // 角色的实体ID(本场景唯一)
    AbilitySyncStateInfo weapon_ability_info = 12; // 武器的技能信息
    uint32 weapon_entity_id = 10;                  // 武器的实体ID(本场景唯一)
    AbilitySyncStateInfo avatar_ability_info = 2;  // 角色的技能信息
    uint64 avatar_guid = 13;                       // 角色的唯一ID
    uint64 weapon_guid = 9;                        // 武器的唯一ID
    repeated uint32 buff_id_list = 5;              // Buff列表
}

// 队伍进入场景时的信息
message TeamEnterSceneInfo {
    AbilityControlBlock ability_control_block = 7;
    AbilitySyncStateInfo team_ability_info = 10; // 队伍技能信息
    uint32 team_entity_id = 15;                  // 队伍实体ID
}

message MPLevelEntityInfo {
    AbilitySyncStateInfo ability_info = 2; // 技能信息
    uint32 entity_id = 11;                 // 大Team entity_id
    uint32 authority_peer_id = 3;          // authrity peer id
}

// 玩家进入场景的信息通知
message PlayerEnterSceneInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 214;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    TeamEnterSceneInfo team_enter_info = 8;              // 队伍进入场景的信息
    uint32 enter_scene_token = 12;
    repeated AvatarEnterSceneInfo avatar_enter_info = 7; // 角色进入场景的信息(场景跳点时不发)
    uint32 cur_avatar_entity_id = 6;                     // 当前角色的实体ID
    MPLevelEntityInfo mp_level_entity_info = 5;          // MP大team的信息
}

message JoinPlayerSceneReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 292;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 target_uid = 12;
}

message JoinPlayerSceneRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 220;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 10;
}

message SceneKickPlayerReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 264;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 target_uid = 6;
}

message SceneKickPlayerRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 238;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 13;
    uint32 target_uid = 10;
}

message SceneKickPlayerNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 211;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 target_uid = 8; // 被踢者
    uint32 kicker_uid = 9; // 踢人者
}

// 玩家攻击只有客户端才创建的entity(目前只支持灌木)
message HitClientTrivialNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 244;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    Vector position = 11;
    uint32 owner_entity_id = 12;
}

// 回到我的大世界请求
message BackMyWorldReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 286;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message BackMyWorldRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 201;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 11;
}

message SeeMonsterReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 228;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 monster_id = 7;
}

message SeeMonsterRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 251;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 9;
}

message AddSeenMonsterNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 223;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 monster_id_list = 12;
}

message AllSeenMonsterNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 271;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 monster_id_list = 4;
}

// 场景时间同步
message SceneTimeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 245;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint64 scene_time = 14; // 玩家个人时间
    bool is_paused = 1;
    uint32 scene_id = 7;
}

// 客户端通知服务器可以跳场景了
message EnterSceneReadyReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 208;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 enter_scene_token = 9; // 进场token
}

// 跳场景准备相应，Req和Rsp之间会收到各种Disappear
message EnterSceneReadyRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 209;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 enter_scene_token = 1;
    int32 retcode = 4;
}

// 在EnterSceneReadyReq和EnterSceneReadyRsp之间收到
message EnterScenePeerNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 252;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 dest_scene_id = 12; // 目标场景ID
    uint32 enter_scene_token = 11;
    uint32 host_peer_id = 14;  // 目标场景的host_peer_id
    uint32 peer_id = 1;        // 在目标场景中的peer_id
}

// 客户端正式进入了场景
message EnterSceneDoneReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 277;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 enter_scene_token = 11; // 进场token
}

// 正式进入场景响应，Req和Rsp之间会收到EntityAppear，触发任务完成等
message EnterSceneDoneRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 237;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 enter_scene_token = 15;
    int32 retcode = 7;
}

// 大世界死亡确认通知
message WorldPlayerDieNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 285;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    PlayerDieType die_type = 12; // 最后一个avatar死亡类型
    uint32 murderer_entity_id = 15;
    oneof entity {
        uint32 monster_id = 8;   // 被怪物杀死
        uint32 gadget_id = 4;    // 被机关弄死
    }
}

// 大世界复活确认
message WorldPlayerReviveReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 225;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

// 大世界复活确认响应
message WorldPlayerReviveRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 278;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 3;
}

// 进入别人的世界失败提示
message JoinPlayerFailNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 236;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 11;
}

// 设置区域天气状态（C->S）
message SetSceneWeatherAreaReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 254;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 weather_gadget_id = 13;             // 天气区域物件ID
    map<uint32, string> weather_value_map = 4; // 不同来源的天气值
}

// 设置区域天气状态的返回（S->C）
message SetSceneWeatherAreaRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 283;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
}

// 客户端请求触发GadgetLua对应的函数: onClientExecuteReq
message ExecuteGadgetLuaReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 269;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 source_entity_id = 12; // 源实体ID, 这个entity必须存在
    int32 param3 = 1;             // 参数3
    int32 param1 = 5;             // 参数1
    int32 param2 = 14;            // 参数2
}

message ExecuteGadgetLuaRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 210;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 12;
}

message CutSceneExtraParam {
    repeated double detail_param_list = 1;
}

// 服务端通知客户端播放cutscene(S->C)
message CutSceneBeginNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 296;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_wait_others = 9; // 是否需要等待其他玩家播放完成
    uint32 cutscene_id = 14;
    repeated CutSceneExtraParam extra_param_list = 3;
}

// 客户端通知服务端CutScene播完(C->S), is_wait_others == true才需要发送
message CutSceneFinishNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 262;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 cutscene_id = 12;
}

// 服务端通知客户端cutscene结束(S->C)
message CutSceneEndNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 215;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 5; // 所有客户端是否正常播放完cutscene
    uint32 cutscene_id = 14;
}

// 客户端通知脚本事件发生(C->S)
message ClientScriptEventNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 213;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated int32 param_list = 9; // 参数列表
    uint32 source_entity_id = 14;  // 事件来源实体ID
    uint32 event_type = 10;        // 事件类型(取值范围：EventType)
    uint32 target_entity_id = 13;  // 事件目标实体ID
}

// 地图上的合包后的实体移动请求
message SceneEntitiesMovesReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 279;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 0;
        IS_ALLOW_CLIENT = 1;
    }

    repeated EntityMoveInfo entity_move_info_list = 14;
}

// Entity移动失败信息
message EntityMoveFailInfo {
    int32 retcode = 12;
    uint32 scene_time = 9;       // 失败时的地图时间
    MotionInfo fail_motion = 14; // 失败时的运动信息
    uint32 reliable_seq = 4;     // 失败时的序列号
    uint32 entity_id = 10;       // 实体ID
}

// 地图上的合包后的实体移动回复(只回复失败的移动)
message SceneEntitiesMovesRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 255;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 0;
    }

    repeated EntityMoveFailInfo entity_move_fail_info_list = 11;
}

// 地图上的合包后的实体移动通知(S->C)
message SceneEntitiesMoveCombineNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3387;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 0;
    }

    repeated EntityMoveInfo entity_move_info_list = 8;
}

// 客户端请求解锁二级传送点
message UnlockTransPointReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3035;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 point_id = 12;
    uint32 scene_id = 10;
}

message UnlockTransPointRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3426;
        ENET_CHANNEL_ID = 1;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 12;
}

// 天气预报请求（C->S）
message SceneWeatherForcastReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3110;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 weather_area_id = 15; // 天气区域ID
}

message SceneWeatherForcastRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3012;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint64 next_climate_time = 14;            // 下一次天气变化的游戏内时间
    repeated uint32 forcast_climate_list = 2; // 用于天气预报的天气类型，间隔为游戏内的2小时
    int32 retcode = 4;
}

// 标记地图请求
message MarkMapReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3466;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    enum Operation {
        ADD = 0; // 添加
        MOD = 1; // 修改
        DEL = 2; // 删除
        GET = 3; // 获取
    }

    MapMarkPoint mark = 8; // 要添加/删除的标记（op==ADD||op==DEL） 替换后的新标记（op==MOD）
    MapMarkPoint old = 6;  // 要替换的旧标记（仅op==MOD时有效）
    Operation op = 9;      // 操作类型
}

// 标记地图响应
message MarkMapRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3079;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated MapMarkPoint mark_list = 8; // 所有的地图标记
    int32 retcode = 11;                  // 返回码
}

// 推送所有地图标记数据
message AllMarkPointNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3283;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated MapMarkPoint mark_list = 7; // 所有的地图标记
}

message WorldDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3308;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    enum DataType {
        DATA_NONE = 0;
        WORLD_LEVEL = 1;
        IS_IN_MP_MODE = 2;
    }

    map<uint32, PropValue> world_prop_map = 9;
}

// 客户端通知服务端Entity的room_id有变化
message EntityMoveRoomNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3178;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 11;
    uint32 dest_room_id = 9;
}

// 玩家进入退出大世界时的广播通知S->C
message WorldPlayerInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3116;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated PlayerWidgetInfo player_widget_info_list = 8;
    repeated OnlinePlayerInfo player_info_list = 14; // 玩家在线数据
    repeated uint32 player_uid_list = 11;            // 玩家uid列表, 用于确定1p, 2p等, 为0表示为空
}

// 客户端进入场景后
message PostEnterSceneReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3312;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 enter_scene_token = 12; // 进场token
}

// 客户端进入场景之后
message PostEnterSceneRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3184;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
    uint32 enter_scene_token = 12;
}

// 聊天内容
message ChatInfo {
    enum SystemHintType {
        CHAT_NONE = 0;
        CHAT_ENTER_WORLD = 1; // 玩家进入大世界
        CHAT_LEAVE_WORLD = 2; // 玩家退出大世界
    }

    message SystemHint {
        uint32 type = 14; // 消息类型
    }

    uint32 time = 13;
    uint32 sequence = 10;
    uint32 to_uid = 7;
    uint32 uid = 15;                   // 玩家uid
    bool is_read = 5;
    oneof content {
        string text = 1946;            // 玩家输入的聊天文本
        uint32 icon = 914;             // 玩家输入的表情数据
        SystemHint system_hint = 1753; // 系统消息通知
    }
}

// 玩家在当前世界中聊天
message PlayerChatReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3185;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 channel_id = 13;
    ChatInfo chat_info = 15; // 聊天内容
}

message PlayerChatRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3228;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 chat_forbidden_endtime = 15;
    int32 retcode = 2; // 返回码
}

// 玩家聊天内容的广播协议
message PlayerChatNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3010;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    ChatInfo chat_info = 3; // 聊天内容
    uint32 channel_id = 6;
}

// 聊天过快进入CD
message PlayerChatCDNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3367;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 over_time = 15; // 结束时间
}

message ChatHistoryNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3496;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ChatInfo chat_info = 9;
    uint32 channel_id = 12;
}

message SceneDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3203;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated string level_config_name_list = 15;
    repeated uint32 scene_tag_id_list = 8;
}

message DungeonEntryToBeExploreNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3147;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 dungeon_entry_scene_point_id = 2; // 地城入口ScenePoint ID
    uint32 scene_id = 4;
    uint32 dungeon_entry_config_id = 10;     // 地城入口配置ID
}

message GetDungeonEntryExploreConditionReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3165;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 scene_id = 6;
    uint32 dungeon_entry_config_id = 2;      // 地城入口配置ID
    uint32 dungeon_entry_scene_point_id = 4; // 地城入口ScenePoint ID
}

message DungeonEntryCond {
    DungeonEntryBlockReason cond_reason = 7;
    uint32 param1 = 8;
}

message GetDungeonEntryExploreConditionRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3269;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    DungeonEntryCond dungeon_entry_cond = 5;
    int32 retcode = 3; // 返回码
}

// 解谜地城
message UnfreezeGroupLimitNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3220;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 point_id = 9;
    uint32 scene_id = 11;
}

// 客户端设置表现用的数据
message SetEntityClientDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3146;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 entity_id = 14;
    EntityClientData entity_client_data = 9; // 不能超过1KB
}

message GroupSuiteNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3257;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    map<uint32, uint32> group_map = 3;
}

message GroupUnloadNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3344;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 group_list = 10;
}

message MonsterAIConfigHashNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3039;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 job_id = 10;
    uint32 entity_id = 15;
    int32 hash_value = 11;
}

message ShowTemplateReminderNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3491;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_revoke = 1;
    uint32 template_reminder_id = 14;
    repeated uint32 param_uid_list = 3;
    repeated int32 param_list = 10;
    bool is_need_cache = 15;
}

message ShowCommonTipsNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3352;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string content = 8;
    string title = 13;
    uint32 close_time = 4;
}

message CloseCommonTipsNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3194;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }
}

message ChangeWorldToSingleModeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3006;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message SyncScenePlayTeamEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3333;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_id = 2;
    repeated PlayTeamEntityInfo entity_info_list = 3;
}

message DelScenePlayTeamEntityNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3318;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 del_entity_id_list = 2;
    uint32 scene_id = 4;
}

message CylinderRegionSize {
    float radius = 8;
    float height = 7;
}

message PolygonRegionSize {
    repeated VectorPlane point_list = 5;
    float height = 9;
}

message PlayerEyePointStateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3051;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 region_entity_id = 15;
    Vector eye_point_pos = 1;
    bool is_use_eye_point = 3;
    uint32 region_config_id = 7;
    uint32 region_shape = 12;
    bool is_filter_stream_pos = 2;
    int32 fix_lod_level = 5;
    uint32 region_group_id = 4;
    oneof region_size {
        float sphere_radius = 255;
        Vector cubic_size = 1823;
        CylinderRegionSize cylinder_size = 1862;
        PolygonRegionSize polygon_size = 877;
    }
}

message GetMapMarkTipsReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3463;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetMapMarkTipsRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3327;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 7;
    repeated MapMarkTipsInfo mark_tips_list = 11;
}

message ChangeWorldToSingleModeReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3066;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message ChangeWorldToSingleModeRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3282;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 quit_mp_valid_time = 15;
    int32 retcode = 4;
}

message GetWorldMpInfoReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3391;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetWorldMpInfoRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3320;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 12;
    bool is_in_mp_mode = 1;
    uint32 quit_mp_valid_time = 9;
}

message EntityConfigHashEntry {
    uint32 job_id = 13;
    int32 hash_value = 6;
    uint32 entity_id = 11;
}

message EntityConfigHashNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3189;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated EntityConfigHashEntry ability_entry_list = 3;
    repeated EntityConfigHashEntry avatar_entry_list = 15;
    repeated EntityConfigHashEntry combat_entry_list = 8;
}

message ForceDragAvatarNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3235;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_time = 3;
    uint64 delta_time_ms = 1;
    uint32 entity_id = 2;
    MotionInfo motion_info = 10;
    bool is_first_valid = 8;
    uint64 last_move_time_ms = 12;
}

message MonsterPointArrayRouteUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3410;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 7;
    MonsterRoute monster_route = 5;
}

message ForceDragBackTransferNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3145;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetScenePerformanceReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3419;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetScenePerformanceRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3137;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 monster_num = 9;
    uint32 gather_num_insight = 1;
    uint32 gadget_num = 6;
    int32 retcode = 7;
    uint32 dynamic_group_num = 12;
    uint32 group_num = 2;
    Vector pos = 4;
    uint32 entity_num = 8;
    uint32 gather_num = 13;
}

message SceneAudioNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3166;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated float param2 = 14;
    int32 type = 3;
    repeated string param3 = 11;
    uint32 source_uid = 6;
    repeated uint32 param1 = 4;
}

message HitTreeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3019;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 tree_type = 11;
    Vector tree_pos = 2;
    Vector drop_pos = 8;
}

message EntityTagChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3316;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string tag = 2;
    uint32 entity_id = 8;
    bool is_add = 10;
}

message AvatarFollowRouteNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3458;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 entity_id = 4;
    uint32 template_id = 6;
    uint32 start_scene_time_ms = 8;
    Route route = 2;
    string client_params = 13;
}

message SceneEntityUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3412;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 param = 10;
    VisionType appear_type = 13;
    repeated SceneEntityInfo entity_list = 5;
}

message ClientHashDebugNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3086;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 job_id = 12;
}

message PlayerWorldSceneInfo {
    uint32 scene_id = 11;
    repeated uint32 scene_tag_id_list = 8;
    bool is_locked = 12;
}

message PlayerWorldSceneInfoListNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3129;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated PlayerWorldSceneInfo info_list = 5;
}

message LuaEnvironmentEffectNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3408;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 type = 1;
    repeated int32 int_param_list = 12;
    string effect_alias = 3;
    repeated float float_param_list = 14;
}

message ClientLoadingCostumeVerificationNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3487;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 costume_id = 9;
    uint64 prefab_hash = 2;
    uint64 guid = 14;
}

message ShowClientGuideNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3005;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string guide_name = 7;
}

message ShowClientTutorialNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3305;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 tutorial_id = 2;
}

message GetMapAreaReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3108;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetMapAreaRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3328;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 14;
    repeated MapAreaInfo map_area_info_list = 9;
}

message MapAreaChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3378;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated MapAreaInfo map_area_info_list = 3;
}

message LeaveWorldNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3017;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }
}

message GuestBeginEnterSceneNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3031;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_id = 8;
    uint32 uid = 15;
}

message GuestPostEnterSceneNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3144;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 scene_id = 5;
    uint32 uid = 4;
}

message LevelTagDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3314;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 level_tag_id_list = 9;
}

message StopReminderNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3004;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 reminder_id = 15;
}

message AreaPlayInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3323;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 detail_play_type = 14;
    AreaPlayType area_play_type = 11;
}

message CheckGroupReplacedReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3113;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 group_id_list = 7;
}

message CheckGroupReplacedRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3152;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
    repeated uint32 replaced_group_id_list = 6;
}

message DeathZoneObserveNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3475;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 target_entity_id = 14;
    uint32 source_entity_id = 12;
}

message HitTreeInfo {
    Vector tree_pos = 12;
    uint32 tree_type = 8;
}

message WorldChestOpenNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3295;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 group_id = 6;
    uint32 scene_id = 9;
    uint32 config_id = 12;
}

message WidgetQuickHitTreeReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3345;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated HitTreeInfo hit_tree_info_list = 5;
}

message WidgetQuickHitTreeRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3336;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 2;
}

message BeginCameraSceneLookWithTemplateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3160;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum FollowType {
        FOLLOW_TYPE_INIT_FOLLOW_POS = 0;
        FOLLOW_TYPE_SET_FOLLOW_POS = 1;
        FOLLOW_TYPE_SET_ABS_FOLLOW_POS = 2;
    }

    Vector look_pos = 8;
    uint32 template_id = 5;
    Vector follow_pos = 2;
    uint32 entity_id = 12;
    repeated string other_params = 13;
    FollowType follow_type = 9;
}

message RefreshEntityAuthNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3259;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated uint32 entity_id_list = 7;
}

message ScenePlayerBackgroundAvatarRefreshNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 3274;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated SceneEntityInfo entity_list = 4;
    VisionType appear_type = 8;
    uint32 param = 9;
}
