// 签到相关协议

syntax = "proto3";

package proto;

import "define.proto";

option go_package = "./;proto";

message OpActivityTagBriefInfo {
    uint32 config_id = 2;
    bool has_reward = 3;
    uint32 op_activity_type = 11;
}

message OpActivityStateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2572;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 finished_bonus_activity_id_list = 14;
    repeated OpActivityTagBriefInfo opened_op_activity_info_list = 13;
}

message SignInData {
    uint32 day_count = 14;
    repeated ItemParam reward_item_list = 5;
}

// 签到排期信息
message SignInInfo {
    bool is_cond_satisfied = 7;           // 是否满足活动开启条件，一旦满足不再检查开启条件
    repeated uint32 reward_day_list = 15; // 领过哪几天的奖励
    repeated SignInData signin_data_list = 12;
    uint32 config_id = 8;                 // 排期用到的签到配置ID
    uint32 sign_in_count = 2;             // 当前排期已累计签到几次
    uint32 schedule_id = 3;               // 排期ID
    uint32 end_time = 13;                 // 当前排期的结束时间
    uint32 last_sign_in_time = 6;         // 上次签到时间
    uint32 begin_time = 5;                // 当前排期的开始时间
}

// 打开签到界面时请求所有签到信息（C->S）
message SignInInfoReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2512;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

// 请求所有签到信息的回复（S->C）
message SignInInfoRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2535;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated SignInInfo sign_in_info_list = 1; // 当前正在进行的或下个未开始的签到信息，长度为0表示没有这样的签到排期
    int32 retcode = 11;
}

// 请求领取签到奖励（C->S）
message GetSignInRewardReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2507;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 schedule_id = 10; // 排期ID
    uint32 reward_day = 3;   // 第几天的奖励
}

// 领取签到奖励的回复（S->C）
message GetSignInRewardRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2521;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 1;
    SignInInfo sign_in_info = 14; // 如果签到成功，进度变化后的签到信息
}

// bonus活动信息
message BonusActivityInfo {
    uint32 bonus_activity_id = 6; // bonus活动配置ID
    uint32 state = 3;             // 进度状态（取值范围：data::BonusActivityState）
}

// bonus状态变化时的通知
message BonusActivityUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2575;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated BonusActivityInfo bonus_activity_info_list = 8; // 状态变化了的bonus活动的信息
}

// 请求bonus活动记录
message BonusActivityInfoReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2548;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message BonusActivityInfoRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2597;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated BonusActivityInfo bonus_activity_info_list = 2; // 所有bonus活动的信息，包括未开始的和已结束的
    int32 retcode = 7;
}

// 领取bonus活动的奖励
message GetBonusActivityRewardReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2581;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 bonus_activity_id = 14; // bonus活动配置ID
}

message GetBonusActivityRewardRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 2505;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    BonusActivityInfo bonus_activity_info_list = 4; // 领奖成功后bonus活动的信息
    int32 retcode = 13;
}
