// 玩家相关协议

syntax = "proto3";

package proto;

import "define.proto";

option go_package = "./;proto";

enum CompoundBoostTakeStatusType {
    COMPOUND_BOOST_TAKE_STATUS_NONE = 0;
    COMPOUND_BOOST_TAKE_STATUS_BOOST_ONLY = 1;
    COMPOUND_BOOST_TAKE_STATUS_BOOST_AND_TAKE = 2;
    COMPOUND_BOOST_TAKE_STATUS_BAG_FULL = 3;
}

// 获取玩家token
message GetPlayerTokenReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 172;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    string account_ext = 9;      // 额外信息
    string account_token = 10;   // token,服务器用来做二次身份验证
    uint32 channel_id = 15;
    bool is_guest = 6;           // 客户端登入时，平台的返回值
    string psn_region = 4;
    uint32 sub_channel_id = 8;
    string account_uid = 11;     // 对应账号的uid
    uint32 key_id = 1787;
    uint32 account_type = 1;     // 账号类型
    uint32 cloud_client_ip = 14; // 玩家通过云游戏APP登录时使用，玩家的真实IP
    uint32 minors_reg_min_age = 995;
    uint32 uid = 2;              // 指定登录某个UID，当该字段被赋值后，account字段会被忽略
    string online_id = 7;
    string birthday = 1718;
    string client_ip_str = 3;
    uint32 platform_type = 12;
    string client_rand_key = 760;
    string country_code = 5;
    uint32 lang = 892;
    string psn_id = 13;
}

message GetPlayerTokenRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 198;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 minors_reg_min_age = 1561;
    uint32 channel_id = 896;
    uint32 platform_type = 8;
    string account_uid = 12;        // 对应账号的uid
    bool is_login_white_list = 573;
    bool is_guest = 4;
    uint32 black_uid_end_time = 14; // 黑名单结束原因
    bool is_watchdog_uid = 2028;
    string psn_id = 1811;
    uint32 tag = 1635;
    string country_code = 2013;
    string token = 11;              // 也是account_token
    uint32 sub_channel_id = 1802;
    bytes security_cmd_buffer = 6;
    string client_version_random_key = 1529;
    string birthday = 937;
    uint64 secret_key_seed = 13;    // 协议加密密钥种子
    uint32 account_type = 5;        // 账号类型
    string msg = 7;                 // 提示信息
    repeated uint32 finish_collection_id_list = 1640;
    string sign = 1140;
    string secret_key = 15;         // 协议加密密钥
    StopServerInfo stop_server = 1382;
    int32 retcode = 2;
    uint32 uid = 1;                 // 游戏内的UID
    bool is_proficient_player = 9;  // 是否是一个老玩家
    uint32 reg_platform = 1112;
    string server_rand_key = 1493;
    bytes extra_bin_data = 3;
    string client_ip_str = 860;
    uint32 gm_uid = 10;             // 免密登入的原始运营uid(仅服务端内部使用)
    uint32 key_id = 1172;
}

message TrackingIOInfo {
    string rydevicetype = 11;
    string mac = 6;
    string deviceid = 9;
    string client_tz = 5;
    string current_caid = 7;
    string cached_caid = 15;
    string appid = 1;
}

message AdjustTrackingInfo {
    string event_token = 9;
    string adid = 4;
    string idfa = 2;
    string app_token = 14;
    string gps_adid = 3;
    string fire_adid = 13;
}

// 玩家登陆请求
message PlayerLoginReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 112;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 language_type = 6;      // 客户端的语言
    uint32 reg_platform = 615;
    TrackingIOInfo tracking_io_info = 1660;
    uint32 account_type = 13;      // 账号类型, gateserver填充
    string token = 15;             // == account_token
    bytes extra_bin_data = 1458;
    uint32 channel_id = 1314;
    uint32 client_data_version = 688;
    string account_uid = 2;        // 对应账号的uid, gateserver填充
    string client_version = 12;    // 客户端版本号
    string security_library_md5 = 772;
    string country_code = 2000;
    string psn_id = 1268;
    uint32 client_port = 431;
    string device_name = 9;        // 设备名称
    string cps = 1163;
    uint64 login_rand = 3;         // 登入随机数
    uint32 target_home_param = 984;
    AdjustTrackingInfo adjust_tracking_info = 1816;
    bool is_transfer = 908;
    uint32 tag = 1787;
    bool is_guest = 5;             // 客户端填充, TODO...替换Token中的is_guest
    bytes environment_error_code = 2026;
    string online_id = 903;
    bool is_editor = 8;            // 是否是unity客户端, gateserver填充
    string checksum_client_version = 861;
    bytes security_cmd_reply = 1995;
    string security_library_version = 1213;
    string birthday = 1652;
    string device_uuid = 4;        // 设备唯一ID
    uint32 client_token = 1546;
    uint32 sub_channel_id = 23;
    uint32 target_uid = 11;        // 进入别人的世界的uid, 服务端设置，客户端不要填充
    string device_info = 1;        // 设备信息，例如samsung SM-G9250
    string client_verison_hash = 1707;
    string checksum = 1532;
    uint32 platform_type = 14;     // 平台类型，PlatformType，如果玩家通过云游戏平台登录，该字段应该是CLOUD_ANDROID或CLOUD_IOS
    uint32 target_home_owner_uid = 1864;
    uint32 cloud_client_ip = 1335; // 玩家通过云游戏APP登录时使用，玩家的真实IP
    uint32 gm_uid = 612;           // 免密登入的原始运营uid(gateserver填充)
    string system_version = 10;    // 系统版本号
    string platform = 7;           // 平台，例如android，ios，pc
}

message ShortAbilityHashPair {
    sfixed32 ability_config_hash = 15;
    sfixed32 ability_name_hash = 1;
}

message PlayerLoginRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 135;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 client_data_version = 1;              // gameserver的数值版本号
    bool is_sc_open = 1429;
    int32 retcode = 15;
    map<uint32, BlockInfo> block_info_map = 571; // 当从save wait加载的时候 会携带部分block数据
    bool is_audit = 1685;
    bool is_transfer = 2018;
    string client_silence_md5 = 1746;            // 静默数值Md5
    ResVersionConfig next_res_version_config = 1573;
    // uint32 res_version_ex = 12;        // 小包资源版本号
    uint32 client_silence_data_version = 6;      // gameserver的数值静默版本号
    uint64 login_rand = 4;                       // 登入随机数
    bool is_new_player = 8;                      // 是否为新创建的账号
    string client_version_suffix = 1047;
    string game_biz = 5;                         // 运营要求的game_biz
    string next_resource_url = 621;
    bool is_relogin = 10;                        // 是否为重新登陆(服务器还有玩家数据的缓存)
    double total_tick_time = 125;
    bool is_enable_client_hash_debug = 932;
    bytes sc_info = 2024;
    int32 ability_hash_code = 12;                // 技能配置hash码
    string register_cps = 2040;
    bool is_login_rsp_split = 1649;
    bool is_use_ability_hash = 2;                // 是否使用技能hash码
    map<string, int32> ability_hash_map = 11;    // 所有技能的hash码，Debug模式下才有效
    repeated ShortAbilityHashPair short_ability_hash_map = 250;
    string client_md5 = 1830;                    // 客户端数值Md5
    string country_code = 1900;
    bool is_data_need_relogin = 951;
    ResVersionConfig res_version_config = 1969;  // TODO...删除res_version/res_md5/is_res_need_relogin
    repeated FeatureBlockInfo feature_block_info_list = 1352;
    string birthday = 624;
    uint32 target_uid = 14;                      // 进入别人的世界的uid
    bytes player_data = 13;                      // 账号数据(服务器内部数据)
    string client_silence_version_suffix = 1299;
    uint32 target_home_owner_uid = 553;
    uint32 player_data_version = 7;              // 消息里再放一份，方便登录的时候校验
}

// 玩家登出请求
message PlayerLogoutReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 107;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    // 登出原因
    enum Reason {
        DISCONNECT = 0;      // 断线
        CLIENT_REQ = 1;      // 客户端主动请求退出
        TIMEOUT = 2;         // 连接超时
        ADMIN_REQ = 3;       // 管理员强制退出
        SERVER_CLOSE = 4;    // 关闭服务
        GM_CLEAR = 5;        // GM CLEAR ALL
        PLAYER_TRANSFER = 6; // 玩家迁移
        CLIENT_CHECKSUM_INVALID = 7;
    }

    Reason reason = 6; // 退出游戏的原因
}

message PlayerLogoutRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 121;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 12;
}

// 服务器->客户端掉线通知
message PlayerLogoutNotify {
    enum CmdId {
        NONE = 0;
        CMD_ID = 103;
    }

    int32 retcode = 13;
}

// 玩家数据通知
message PlayerDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 190;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint64 server_time = 7;               // 服务器时间(1970.1.1开始的毫秒数)
    string nick_name = 8;
    bool is_first_login_today = 12;       // 是否是当日的首次登陆
    uint32 region_id = 6;                 // 分区ID
    map<uint32, PropValue> prop_map = 15; // 玩家属性列表
}

// 修改游戏时间
message ChangeGameTimeReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 173;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 game_time = 6;   // 游戏时间
    bool is_force_set = 11; // 是否无视时间锁，强制设置时间
    uint32 extra_days = 12;
}

message ChangeGameTimeRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 199;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 8;
    uint32 extra_days = 5;
    uint32 cur_game_time = 14; // 当前的游戏时间
}

// 玩家的游戏时间通知
message PlayerGameTimeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 131;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 uid = 7;       // 所属玩家的uid
    uint32 game_time = 3; // 当前游戏时间(首次登录当天0点开始的秒数，离线后不计时)
    bool is_home = 13;
}

// 玩家的属性通知(改变后通知)
message PlayerPropNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 175;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    map<uint32, PropValue> prop_map = 13; // 属性列表
}

// 客户端触发事件通知(C->S)
message ClientTriggerEventNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 148;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 force_id = 3;
    EventTriggerType event_type = 2;
}

// 设置玩家属性(允许客户端修改的才能通过)
message SetPlayerPropReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 197;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated PropValue prop_list = 7; // 改变的属性列表
}

message SetPlayerPropRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 181;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 11;
}

// 设置玩家出生数据
// TODO 临时方案，以后会做成正式的角色性别选取
message SetPlayerBornDataReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 105;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 avatar_id = 2;
    string nick_name = 13;
}

message SetPlayerBornDataRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 182;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 10;
}

// 通知客户端进行新账号初始化 S->C
message DoSetPlayerBornDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 147;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }
}

// 经验变化时用于同步变化量，客户端用来做表现
message PlayerPropChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 139;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 prop_delta = 13; // 变化量
    uint32 prop_type = 12;  // 属性类型（目前只有经验）
}

// 设置玩家名字
message SetPlayerNameReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 153;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    string nick_name = 1;
}

message SetPlayerNameRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 122;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 9;
    string nick_name = 14;
}

message SetOpenStateReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 165;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 key = 12;
    uint32 value = 5;
}

message SetOpenStateRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 104;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 key = 9;
    int32 retcode = 14;
    uint32 value = 15;
}

message OpenStateUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 193;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    map<uint32, uint32> open_state_map = 6;
}

message OpenStateChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 127;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    map<uint32, uint32> open_state_map = 4;
}

// 烹饪
message PlayerCookReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 194;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 cook_count = 1;
    uint32 qte_quality = 12;   // QTE的结果, 0表示自动烹饪
    uint32 recipe_id = 8;      // 食谱编号
    uint32 assist_avatar = 14; // 辅助avatar
}

message PlayerCookRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 188;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ItemParam extral_item_list = 15;
    uint32 cook_count = 12;
    repeated ItemParam item_list = 11;
    int32 retcode = 3;
    uint32 qte_quality = 5;         // QTE的结果
    CookRecipeData recipe_data = 7; // 食谱数据
}

// 乱炖
message PlayerRandomCookReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 126;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated ItemParam material_list = 13;
}

message PlayerRandomCookRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 163;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
}

// 烹饪全部数据
message CookRecipeData {
    uint32 proficiency = 13; // 熟练度
    uint32 recipe_id = 9;
}

message CookDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 195;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated CookRecipeData recipe_data_list = 2; // 全部的食谱数据,包括默认解锁的食谱id
    uint32 grade = 11;                            // 段位
}

// 食谱数据变更
message CookRecipeDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 106;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    CookRecipeData recipe_data = 4; // 变更的食谱数据
}

// 烹饪段位同步
message CookGradeDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 134;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 grade = 12;
}

// 材料合成
message PlayerCompoundMaterialReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 150;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 count = 11; // 合成数量
    uint32 compound_id = 3;
}

// 合成生产线数据
message CompoundQueueData {
    uint32 output_count = 1; // 已经完成的数量
    uint32 compound_id = 4;
    uint32 output_time = 14; // 下一个完成合成的时间
    uint32 wait_count = 8;   // 等待合成的数量
}

message PlayerCompoundMaterialRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 143;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    CompoundQueueData compound_que_data = 5;
    int32 retcode = 12;
}

// 领取合成结果
message TakeCompoundOutputReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 174;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 compound_group_id = 3;
    uint32 compound_id = 10;
}

message TakeCompoundOutputRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 176;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ItemParam item_list = 6;
    int32 retcode = 2;
}

// 合成组件的全部数据
message CompoundDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 146;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 unlock_compound_list = 1; // 包括默认解锁的合成id
    repeated CompoundQueueData compound_que_data_list = 9;
}

// 客户端主动拉取合成数据
message GetCompoundDataReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 141;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetCompoundDataRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 149;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 3;
    repeated uint32 unlock_compound_list = 11; // 包括默认解锁的合成id
    repeated CompoundQueueData compound_que_data_list = 7;
}

// 玩家个人时间同步
message PlayerTimeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 191;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint64 server_time = 5;  // 服务器时间(1970.1.1开始的毫秒数)
    uint64 player_time = 11; // 玩家个人时间
    bool is_paused = 14;
}

// 玩家暂停请求
message PlayerSetPauseReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 124;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_paused = 1;
}

// 玩家暂停响应
message PlayerSetPauseRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 156;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 15;
}

message PlayerSetLanguageReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 142;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 language_type = 5;
}

message PlayerSetLanguageRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 130;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 11;
}

message DataResVersionNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 167;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    enum DataResVersionOpType {
        OP_TYPE_NONE = 0;
        OP_TYPE_RELOGIN = 1;
        OP_TYPE_MP_RELOGIN = 2;
    }

    string client_silence_md5 = 10;
    string client_silence_version_suffix = 15;
    ResVersionConfig res_version_config = 9; // TODO...删除res_version/res_md5/is_res_need_relogin
    bool is_data_need_relogin = 7;
    DataResVersionOpType op_type = 12;
    uint32 client_data_version = 2;          // 客户端非静默数值版本
    string client_version_suffix = 5;
    uint32 client_silence_data_version = 1;  // 客户端静默数值版本
    // uint32 res_version_ex = 4;              // 小包资源版本号
    string client_md5 = 14;
}

message DailyTaskInfo {
    uint32 reward_id = 3;        // 客户端展示用的reward_id
    uint32 progress = 13;        // 当前进度
    uint32 finish_progress = 10; // 完成需要的进度
    uint32 daily_task_id = 4;
    bool is_finished = 14;       // 是否完成
}

message DailyTaskDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 158;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    // repeated DailyTaskInfo task_list = 1;   // 今天的事件列表
    // repeated uint32 finished_task_list = 2; // 已经完成的事件列表
    uint32 score_reward_id = 11;    // 积分奖励
    uint32 finished_num = 4;        // 完成次数
    bool is_taken_score_reward = 9; // 是否领取了积分奖励
}

message DailyTaskProgressNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 170;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    DailyTaskInfo info = 12;
}

// 积分奖励的通知
message DailyTaskScoreRewardNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 117;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 reward_id = 14;
}

// 主机同步给客机的固定事件
message WorldOwnerDailyTaskNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 102;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    repeated DailyTaskInfo task_list = 1; // 主机事件列表
    uint32 finished_daily_task_num = 5;
    uint32 filter_city_id = 2;
}

// 通知客户端增加一个随机事件
message AddRandTaskInfoNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 119;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 rand_task_id = 5;
    Vector pos = 13;
}

// 通知客户端移除一个随机事件
message RemoveRandTaskInfoNotify {
    enum FinishReason {
        DEFAULT = 0;
        CLEAR = 1;    // GM指令清理
        DISTANCE = 2; // 远距离销毁
        FINISH = 3;   // 玩家完成
    }

    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 161;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_succ = 9;
    FinishReason reason = 10;
    uint32 rand_task_id = 13;
}

// 领取等级奖励
message TakePlayerLevelRewardReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 129;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 level = 3;
}

message TakePlayerLevelRewardRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 157;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 reward_id = 9;
    int32 retcode = 13;
    uint32 level = 6;
}

message PlayerLevelRewardUpdateNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 200;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 level_list = 9;
}

// 道具交付记录
message GivingRecord {
    bool is_finished = 9;
    uint32 group_id = 5;
    bool is_gadget_giving = 8;
    uint32 giving_id = 3;
    uint32 last_group_id = 6;
    uint32 config_id = 2;
    map<uint32, uint32> material_cnt_map = 15;
}

// 登录时通知所有交付记录
message GivingRecordNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 116;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated GivingRecord giving_record_list = 14;
}

// 交付记录变化通知
message GivingRecordChangeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 187;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_deactive = 11;
    GivingRecord giving_record = 15;
}

// 请求交付道具
message ItemGivingReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 140;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    enum ItemGivingType {
        QUEST = 0;
        GADGET = 1;
    }

    map<uint64, uint32> item_guid_count_map = 15;
    uint32 giving_id = 13;
    repeated ItemParam item_param_list = 4;
    ItemGivingType item_giving_type = 2;
}

message ItemGivingRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 118;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 giving_group_id = 1;
    uint32 giving_id = 13;
    int32 retcode = 3;
}

// 烹饪开始时请求相关参数
message PlayerCookArgsReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 166;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 assist_avatar = 10; // 辅助avatar
    uint32 recipe_id = 11;     // 食谱ID
}

message PlayerCookArgsRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 168;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 4;
    float qte_range_ratio = 12; // QTE完美玩法增加系数：生效的得意技能加的最大值
}

// 通知客户端执行luashell G --> C
message PlayerLuaShellNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 133;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    LuaShellType shell_type = 7;
    uint32 id = 5;        // 对应添加到数据库里面的id 唯一标识
    bytes lua_shell = 12; // lua 内容
    uint32 use_type = 10;
}

message ServerDisconnectClientNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 184;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 data = 10; // ENetReason
}

message AntiAddictNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 180;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 msg_type = 6;
    string msg = 3;
    string level = 5;
}

message PlayerForceExitReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 189;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message PlayerForceExitRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 159;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 15;
}

message PlayerInjectFixNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 132;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 id = 13;
    bytes inject_fix = 10;
}

message TaskVar {
    uint32 key = 8;
    repeated int32 value_list = 6;
}

message TaskVarNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 160;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated TaskVar task_var_list = 7;
}

message ClientLockGameTimeNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 114;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_lock = 5;
}

message GetNextResourceInfoReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 192;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message GetNextResourceInfoRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 120;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string next_resource_url = 14;
    ResVersionConfig next_res_version_config = 2;
    int32 retcode = 12;
}

message AdjustWorldLevelReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 164;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 expect_world_level = 8;
    uint32 cur_world_level = 9;
}

message AdjustWorldLevelRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 138;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 13;
    uint32 cd_over_time = 15;
    uint32 after_world_level = 14;
}

message DailyTaskFilterCityReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 111;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 city_id = 8;
}

message DailyTaskFilterCityRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 144;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 5;
    uint32 city_id = 9;
}

message DailyTaskUnlockedCitiesNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 186;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated uint32 unlocked_city_list = 12;
}

message ExclusiveRuleInfo {
    repeated uint32 object_id_list = 1;
    uint32 rule_type = 10;
}

message ExclusiveRuleNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 101;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ExclusiveRuleInfo rule_info_list = 5;
}

message CompoundUnlockNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 128;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 compound_id = 3;
}

message GameplayRecommendationSkillRequest {
    uint32 skill_depot_id = 1;
}

message GameplayRecommendationReliquaryRequest {
    uint32 equip_type = 6;
}

message GameplayRecommendationElementReliquaryRequest {
    uint32 equip_type = 9;
    uint32 element_type = 12;
}

message GetGameplayRecommendationReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 151;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 avatar_id = 9;
    oneof detail {
        GameplayRecommendationSkillRequest skill_request = 553;
        GameplayRecommendationReliquaryRequest reliquary_request = 1993;
        GameplayRecommendationElementReliquaryRequest element_reliquary_request = 1489;
    }
}

message GameplayRecommendationSkillResponse {
    uint32 skill_depot_id = 13;
    repeated uint32 skill_id_list = 9;
}

message GameplayRecommendationReliquaryMainPropData {
    uint32 permillage = 1;
    uint32 main_prop_id = 12;
}

message GameplayRecommendationReliquaryResponse {
    repeated GameplayRecommendationReliquaryMainPropData main_prop_data_list = 8;
    uint32 equip_type = 3;
}

message GameplayRecommendationElementReliquaryResponse {
    uint32 element_type = 11;
    repeated GameplayRecommendationReliquaryMainPropData main_prop_data_list = 5;
    uint32 equip_type = 15;
}

message GetGameplayRecommendationRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 123;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 6;
    uint32 avatar_id = 15;
    oneof detail {
        GameplayRecommendationSkillResponse skill_response = 1022;
        GameplayRecommendationReliquaryResponse reliquary_response = 196;
        GameplayRecommendationElementReliquaryResponse element_reliquary_response = 167;
    }
}

message TakeBackGivingItemReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 171;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    uint32 giving_id = 4;
}

message TakeBackGivingItemRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 145;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 giving_id = 10;
    int32 retcode = 6;
}

message PlayerNicknameAuditDataNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 108;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    ContentAuditInfo info = 13;
}

message PlayerNicknameNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 109;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string nickname = 7;
}

message NicknameAuditConfigNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 152;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    bool is_open = 8;
    uint32 submit_limit = 12;
}

message ReadNicknameAuditReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 177;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }
}

message ReadNicknameAuditRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 137;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    int32 retcode = 12;
}

message PlayerCompoundMaterialBoostReq {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 185;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
        IS_ALLOW_CLIENT = 1;
    }

    bool is_boost_all = 8;
    uint32 target_compound_group_id = 14;
    uint32 consume_material_id = 9;
    uint32 consume_material_count = 1;
}

message PlayerCompoundMaterialBoostRsp {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 125;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    repeated ItemParam take_item_list = 2;
    CompoundBoostTakeStatusType take_status = 6;
    int32 retcode = 7;
    repeated CompoundQueueData compound_que_data_list = 1;
}

message PlayerGameTimeByLuaNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 178;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    uint32 uid = 13;
    uint32 sim_speed = 9;
    uint32 game_time = 10;
}

message PlayerIpRegionNotify {
    enum CmdId {
        option allow_alias = true;
        NONE = 0;
        CMD_ID = 136;
        ENET_CHANNEL_ID = 0;
        ENET_IS_RELIABLE = 1;
    }

    string ip_code = 9;
}
